import 'package:masalah/presentation/screens/al_quran/data/juz.dart';
import 'package:masalah/presentation/screens/al_quran/data/surah.dart';

class AlQuranConstant {
  AlQuranConstant._();

  static List<Juz> juzs = [
    new Juz(
        page: 2,
        arbTitle: "آلم",
        enTitle: "Alif Lam Meem ",
        enJuz: "1:1-2:74",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 23,
        arbTitle: "سَيَقُولُ",
        enTitle: "Sayaqool",
        enJuz: "2:142 - 2:252 ",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 43,
        arbTitle: "تِلْكَ ٱلْرُّسُلُ",
        enTitle: "Tilkal Rusulu",
        enJuz: "2:253 - 3:92",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 63,
        arbTitle: "لَنْ تَنَالُوْ الْبِرَّ",
        enTitle: "Lan tanaloo albirra",
        enJuz: "3:93 - 4:23",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 83,
        arbTitle: "وَٱلْمُحْصَنَاتُ",
        enTitle: "Wal Mohsanatu",
        enJuz: "4:24 - 4:147",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 103,
        arbTitle: "لَا يُحِبُّ ٱللهُ",
        enTitle: "La Yuhibbullah",
        enJuz: "4:148 - 5:81",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 123,
        arbTitle: "وَإِذَا سَمِعُوا",
        enTitle: "Wa Iza Samiu",
        enJuz: "5:82 - 6:110",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 143,
        arbTitle: "وَلَوْ أَنَّنَا",
        enTitle: "Wa Lau Annana",
        enJuz: "6:111 - 7:87",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 163,
        arbTitle: "قَالَ ٱلْمَلَأُ",
        enTitle: "Qalal Malao",
        enJuz: "7:88 - 6:110",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 183,
        arbTitle: "وَٱعْلَمُواْ",
        enTitle: "Wa A'lamu",
        enJuz: "8:41 - 7:87",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 203,
        arbTitle: "يَعْتَذِرُونَ",
        enTitle: "Yatazeroon",
        enJuz: "9:93 - 11:5",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 223,
        arbTitle: "وَمَا مِنْ دَآبَّةٍ",
        enTitle: "Wa Mamin Da'abatin",
        enJuz: "11:6 - 12:52",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 243,
        arbTitle: "وَمَا أُبَرِّئُ",
        enTitle: "Wa Ma Ubrioo",
        enJuz: "12:53 - 14:52",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 263,
        arbTitle: "رُبَمَا",
        enTitle: "Rubama",
        enJuz: "15:1 - 16:128",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 283,
        arbTitle: "سُبْحَانَ ٱلَّذِى",
        enTitle: "Subhan iladhi",
        enJuz: "17:1 - 18:74",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 303,
        arbTitle: "قَالَ أَلَمْ",
        enTitle: "Qala Alam",
        enJuz: "18:75 - 20:135",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 323,
        arbTitle: "ٱقْتَرَبَ لِلْنَّاسِ",
        enTitle: "Iqtaraba li’n",
        enJuz: "asi - 21:1 - 22:78 ",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 343,
        arbTitle: "قَدْ أَفْلَحَ",
        enTitle: "Qadd Aflaha",
        enJuz: "23-1 - 25:20 ",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 363,
        arbTitle: "وَقَالَ ٱلَّذِينَ",
        enTitle: "Wa Qala illadhina",
        enJuz: "25:21 - 27:55",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 383,
        arbTitle: "أَمَّنْ خَلَقَ",
        enTitle: "A'man Khalaqa",
        enJuz: "27:56 - 29:45",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 403,
        arbTitle: "أُتْلُ مَاأُوْحِیَ",
        enTitle: "Utlu Ma Oohiya",
        enJuz: "29:46 - 33:30",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 423,
        arbTitle: "وَمَنْ يَّقْنُتْ",
        enTitle: "Wa-Man yaqnut",
        enJuz: "33:31 - 36:27",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 443,
        arbTitle: "وَمَآ لي",
        enTitle: "Wa Mali",
        enJuz: "36:28 - 39:31",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 463,
        arbTitle: "فَمَنْ أَظْلَمُ",
        enTitle: "Fa-man Azlamu",
        enJuz: "39:32 - 41:46",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 483,
        arbTitle: "إِلَيْهِ يُرَدُّ",
        enTitle: "Ilayhi Yuruddu",
        enJuz: "41:47 - 45:37",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 503,
        arbTitle: "حم",
        enTitle: "Ha Meem",
        enJuz: "46:1 - 51:30",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 523,
        arbTitle: "قَالَ فَمَا خَطْبُكُم",
        enTitle: "Qala Fama Khatbukum",
        enJuz: "51:31 - 57:29",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 543,
        arbTitle: "قَدْ سَمِعَ ٱللهُ",
        enTitle: "Qadd Sami Allah",
        enJuz: "58:1 - 66:12",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 563,
        arbTitle: "تَبَارَكَ ٱلَّذِى",
        enTitle: "Tabaraka lladhi",
        enJuz: "67:1 - 77:50",
        mmJuz: "",
        mmTitle: ""),
    new Juz(
        page: 587,
        arbTitle: "عَمَّ",
        enTitle: "Amma",
        enJuz: "78:1 - 114:6",
        mmJuz: "",
        mmTitle: ""),
  ];

  static List<Surah> surahs = [
    new Surah(
        toPage: 2,
        entitle: "Al-Fatiha",
        arbtitle: 'سُوْرَۃُ الفَاتِحَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Opening)"),
    new Surah(
        toPage: 3,
        entitle: "Al-Baqarah",
        arbtitle: 'سُوْرَۃُ البَقَرَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Cow)"),
    new Surah(
        toPage: 51,
        entitle: "Al-Imran",
        arbtitle: 'سُوْرَۃ آلِ عِمْرَان',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Family Of Imran)"),
    new Surah(
        toPage: 78,
        entitle: "An-Nisa",
        arbtitle: 'سُوْرَۃُ النِّسَاء',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Women)"),
    new Surah(
        toPage: 107,
        entitle: "Al-Maidah",
        arbtitle: 'سُوْرَۃُ المَائِدَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Table Spread)"),
    new Surah(
        toPage: 129,
        entitle: "Al-An'am",
        arbtitle: 'سُوْرَۃُ الأَنْعَام',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Cattle)"),
    new Surah(
        toPage: 152,
        entitle: "Al-A'raf",
        arbtitle: 'سُوْرَۃُ الأَعْرَاف',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Heights)"),
    new Surah(
        toPage: 178,
        entitle: "Al-Anfal",
        arbtitle: 'سُوْرَۃُ الأَنْفَال',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Spoils of War)"),
    new Surah(
        toPage: 188,
        entitle: "Al-Taubah",
        arbtitle: 'سُوْرَۃُ التَّوْبَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Repentance)"),
    new Surah(
        toPage: 209,
        entitle: "Yunus",
        arbtitle: 'سُوْرَۃ يُونُس',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Prophet Jonah)"),
    new Surah(
        toPage: 222,
        entitle: "Hud",
        arbtitle: 'سُوْرَۃ هُود',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Prophet Hud)"),
    new Surah(
        toPage: 236,
        entitle: "Yusuf",
        arbtitle: 'سُوْرَۃ يُوسُف',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Prophet Joseph)"),
    new Surah(
        toPage: 250,
        entitle: "Ar-Rad",
        arbtitle: 'سُوْرَۃ الرَّعْد',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Thunder)"),
    new Surah(
        toPage: 256,
        entitle: "Ibrahim",
        arbtitle: 'سُوْرَۃُ إِبْرَاهِيم',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Prophet Abraham)"),
    new Surah(
        toPage: 262,
        entitle: "Al-Hijr",
        arbtitle: 'سُوْرَۃُ الحِجْر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Rocky Tract)"),
    new Surah(
        toPage: 268,
        entitle: "An-Nahl",
        arbtitle: 'سُوْرَۃُ النَّحْل',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Bee)"),
    new Surah(
        toPage: 283,
        entitle: "Al-Isra",
        arbtitle: 'سُوْرَۃُ الإِسْرَاء',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Night Journey)"),
    new Surah(
        toPage: 294,
        entitle: "Al-Kahf",
        arbtitle: 'سُوْرَۃ الكَهْف',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Cave)"),
    new Surah(
        toPage: 306,
        entitle: "Maryam",
        arbtitle: 'سُوْرَۃ مَرْيَم',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Mary)"),
    new Surah(
        toPage: 313,
        entitle: "Ta-Ha",
        arbtitle: 'سُوْرَۃ طٰهٰ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Ta-Ha)"),
    new Surah(
        toPage: 323,
        entitle: "Al-Anbiya",
        arbtitle: 'سُوْرَۃُ الأَنْبِيَاء',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Prophets)"),
    new Surah(
        toPage: 332,
        entitle: "Al-Hajj",
        arbtitle: 'سُوْرَۃ الحَجّ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Pilgrimage)"),
    new Surah(
        toPage: 343,
        entitle: "Al-Mu'minun",
        arbtitle: 'سُوْرَۃُ المُؤْمِنُون',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Believers)"),
    new Surah(
        toPage: 351,
        entitle: "Al-Noor",
        arbtitle: 'سُوْرَۃ النُّور',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Light)"),
    new Surah(
        toPage: 360,
        entitle: "Al-Furqan",
        arbtitle: 'سُوْرَۃ الفُرْقَان',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Criterian)"),
    new Surah(
        toPage: 367,
        entitle: "Al-Shuara",
        arbtitle: 'سُوْرَۃُ الشُّعَرَاء',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Poets)"),
    new Surah(
        toPage: 377,
        entitle: "Al-Naml",
        arbtitle: 'سُوْرَۃُ النَّمْل',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Ants)"),
    new Surah(
        toPage: 386,
        entitle: "Al-Qasas",
        arbtitle: 'سُوْرَۃُ القَصَص',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Stories)"),
    new Surah(
        toPage: 397,
        entitle: "Al-Ankaboot",
        arbtitle: 'سُوْرَۃُ العَنْكَبُوت',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Spider)"),
    new Surah(
        toPage: 405,
        entitle: "Al-Room",
        arbtitle: 'سُوْرَۃ الرُّوم',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Romans)"),
    new Surah(
        toPage: 412,
        entitle: "Luqman",
        arbtitle: 'سُوْرَۃ لُقْمَان',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Luqman)"),
    new Surah(
        toPage: 416,
        entitle: "As-Sajda",
        arbtitle: 'سُوْرَۃُ السَّجْدَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Adoration)"),
    new Surah(
        toPage: 419,
        entitle: "Al-Ahzab",
        arbtitle: 'سُوْرَۃُ الأَحْزَاب',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Coalition)"),
    new Surah(
        toPage: 429,
        entitle: "Saba",
        arbtitle: 'سُوْرَۃ سَبَأ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Sheva)"),
    new Surah(
        toPage: 435,
        entitle: "Fatir",
        arbtitle: 'سُوْرَۃ فَاطِر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Originator)"),
    new Surah(
        toPage: 441,
        entitle: "Ya-Seen",
        arbtitle: 'سُوْرَۃ يٰس',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Yaseen)"),
    new Surah(
        toPage: 446,
        entitle: "As-Saaffat",
        arbtitle: 'سُوْرَۃُ الصَّافَّات',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Those Who Set The Ranks)"),
    new Surah(
        toPage: 453,
        entitle: "Sad",
        arbtitle: 'سُوْرَۃ ص',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Arabic Letter Sad)"),
    new Surah(
        toPage: 459,
        entitle: "Az-Zumar",
        arbtitle: 'سُوْرَۃُ الزُّمَر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Companies)"),
    new Surah(
        toPage: 468,
        entitle: "Al-Mu'min",
        arbtitle: 'سُوْرَۃ غَافِر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Believer)"),
    new Surah(
        toPage: 478,
        entitle: "Fussilat",
        arbtitle: 'سُوْرَۃ فُصِّلَت',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Explained in Detail)"),
    new Surah(
        toPage: 484,
        entitle: "Ash-Shura",
        arbtitle: 'سُوْرَۃُ الشُّورىٰ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Council)"),
    new Surah(
        toPage: 490,
        entitle: "Az-Zukhruf",
        arbtitle: 'سُوْرَۃُ الزُّخْرُف',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Ornaments of Gold)"),
    new Surah(
        toPage: 496,
        entitle: "Ad-Dukhan",
        arbtitle: 'سُوْرَۃ الدُّخَان',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Drought)"),
    new Surah(
        toPage: 499,
        entitle: "Al-Jasiyah",
        arbtitle: 'سُوْرَۃ الجَاثِيَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Kneeling)"),
    new Surah(
        toPage: 503,
        entitle: "Al-Ahqaf",
        arbtitle: 'سُوْرَۃُ الأَحْقَاف',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Sandhills)"),
    new Surah(
        toPage: 507,
        entitle: "Muhammad",
        arbtitle: 'سُوْرَۃ مُحَمَّد',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Muhammad)"),
    new Surah(
        toPage: 512,
        entitle: "Al-Fath",
        arbtitle: 'سُوْرَۃُ الفَتْح',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Victory)"),
    new Surah(
        toPage: 516,
        entitle: "Al-Hujuraat",
        arbtitle: 'سُوْرَۃُ الحُجُرَات',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Apartments)"),
    new Surah(
        toPage: 519,
        entitle: "Qaf",
        arbtitle: 'سُوْرَۃ ق',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Letter Qaf)"),
    new Surah(
        toPage: 521,
        entitle: "Adh-Dhariyat",
        arbtitle: 'سُوْرَۃُ الذَّارِيَات',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Scatterers)"),
    new Surah(
        toPage: 524,
        entitle: "At-Tur",
        arbtitle: 'سُوْرَۃ الطُّور',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Mountain)"),
    new Surah(
        toPage: 527,
        entitle: "An-Najm",
        arbtitle: 'سُوْرَۃُ النَّجْم',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Star)"),
    new Surah(
        toPage: 529,
        entitle: "Al-Qamar",
        arbtitle: 'سُوْرَۃُ القَمَر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Moon)"),
    new Surah(
        toPage: 532,
        entitle: "Ar-Rahman",
        arbtitle: 'سُوْرَۃ الرَّحْمَٰن',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Most Gracious)"),
    new Surah(
        toPage: 535,
        entitle: "Al-Waqiah",
        arbtitle: 'سُوْرَۃُ الوَاقِعَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Event)"),
    new Surah(
        toPage: 538,
        entitle: "Al-Hadid",
        arbtitle: 'سُوْرَۃُ الحَدِيد',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Iron)"),
    new Surah(
        toPage: 543,
        entitle: "Al-Mujadilah",
        arbtitle: 'سُوْرَۃُ المُجَادِلَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Pleading Woman)"),
    new Surah(
        toPage: 546,
        entitle: "Al-Hashr",
        arbtitle: 'سُوْرَۃُ الحَشْر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Banishment)"),
    new Surah(
        toPage: 550,
        entitle: "Al-Mumtahanah",
        arbtitle: 'سُوْرَۃُ المُمْتَحَنَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Woman Who Is Examined)"),
    new Surah(
        toPage: 552,
        entitle: "As-Saff",
        arbtitle: 'سُوْرَۃُ الصَّفّ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Ranks)"),
    new Surah(
        toPage: 554,
        entitle: "Al-Jumua",
        arbtitle: 'سُوْرَۃُ الجُمُعَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Congregation - Friday)"),
    new Surah(
        toPage: 555,
        entitle: "Al-Munafiqoon",
        arbtitle: 'سُوْرَۃُ المُنَافِقُون',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Hypocrites)"),
    new Surah(
        toPage: 557,
        entitle: "At-Taghabun",
        arbtitle: 'سُوْرَۃُ التَّغَابُن',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Manifestation of Losses)"),
    new Surah(
        toPage: 559,
        entitle: "At-Talaq",
        arbtitle: 'سُوْرَۃُ الطَّلَاق',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Divorce)"),
    new Surah(
        toPage: 561,
        entitle: "At-Tahrim",
        arbtitle: 'سُوْرَۃُ التَّحْرِيم',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Prohibition)"),
    new Surah(
        toPage: 563,
        entitle: "Al-Mulk",
        arbtitle: 'سُوْرَۃُ المُلْك',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Kingdom)"),
    new Surah(
        toPage: 565,
        entitle: "Al-Qalam",
        arbtitle: 'سُوْرَۃ القَلَم',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Pen)"),
    new Surah(
        toPage: 568,
        entitle: "Al-Haqqah",
        arbtitle: 'سُوْرَۃ الحَاقَّة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Sure Truth)"),
    new Surah(
        toPage: 570,
        entitle: "Al-Ma'arij",
        arbtitle: 'سُوْرَۃُ المَعَارِج',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Ways of Ascent)"),
    new Surah(
        toPage: 572,
        entitle: "Nuh",
        arbtitle: 'سُوْرَۃ نُوح',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Prophet Noah)"),
    new Surah(
        toPage: 574,
        entitle: "Al-Jinn",
        arbtitle: 'سُوْرَۃُ الجِنّ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Jinn)"),
    new Surah(
        toPage: 577,
        entitle: "Al-Muzzammil",
        arbtitle: 'سُوْرَۃُ المُزَّمِّل',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The One Covering Himself)"),
    new Surah(
        toPage: 579,
        entitle: "Al-Muddaththir",
        arbtitle: 'سُوْرَۃُ المُدَّثِّر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The One Wrapping Himself Up)"),
    new Surah(
        toPage: 581,
        entitle: "Al-Qiyamah",
        arbtitle: 'سُوْرَۃُ القِيَامَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Resurrection)"),
    new Surah(
        toPage: 583,
        entitle: "Al-Insan",
        arbtitle: 'سُوْرَۃُ الإِنْسَان',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Man)"),
    new Surah(
        toPage: 585,
        entitle: "Al-Mursalaat",
        arbtitle: 'سُوْرَۃُ المُرْسَلَات',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Those sent forth)"),
    new Surah(
        toPage: 587,
        entitle: "An-Naba",
        arbtitle: 'سُوْرَۃُ النَّبَأ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The News)"),
    new Surah(
        toPage: 588,
        entitle: "An-Naziat",
        arbtitle: 'سُوْرَۃُ النَّازِعَات',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Those Who Pull Out)"),
    new Surah(
        toPage: 590,
        entitle: "Abasa",
        arbtitle: 'سُوْرَۃ عَبَسَ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(He Frowned)"),
    new Surah(
        toPage: 591,
        entitle: "At-Takwir",
        arbtitle: 'سُوْرَۃُ التَّكْوِير',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Overthrowing)"),
    new Surah(
        toPage: 592,
        entitle: "Al-Infitaar",
        arbtitle: 'سُوْرَۃُ الإِنْفِطَار',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Splitting Asunder)"),
    new Surah(
        toPage: 593,
        entitle: "Al-Mutaffifin",
        arbtitle: 'سُوْرَۃُ المُطَفِّفِين',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Defrauding)"),
    new Surah(
        toPage: 595,
        entitle: "Al-Inshiqaq",
        arbtitle: 'سُوْرَۃُ الإِنْشِقَاق',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Splitting Asunder)"),
    new Surah(
        toPage: 596,
        entitle: "Al-Burooj",
        arbtitle: 'سُوْرَۃُ البُرُوج',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Big Stars)"),
    new Surah(
        toPage: 597,
        entitle: "At-Tariq",
        arbtitle: 'سُوْرَۃُ الطَّارِق',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Night Comer)"),
    new Surah(
        toPage: 598,
        entitle: "Al-Ala",
        arbtitle: 'سُوْرَۃُ الأَعْلَىٰ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Most High)"),
    new Surah(
        toPage: 598,
        entitle: "Al-Ghaashiyah",
        arbtitle: 'سُوْرَۃُ الغَاشِيَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Overwhelming)"),
    new Surah(
        toPage: 599,
        entitle: "Al-Fajr",
        arbtitle: 'سُوْرَۃُ الفَجْر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Dawn)"),
    new Surah(
        toPage: 601,
        entitle: "Al-Balad",
        arbtitle: 'سُوْرَۃُ البَلَد',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The City)"),
    new Surah(
        toPage: 601,
        entitle: "Ash-Shams",
        arbtitle: 'سُوْرَۃُ الشَّمْس',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Sun)"),
    new Surah(
        toPage: 602,
        entitle: "Al-Lail",
        arbtitle: 'سُوْرَۃُ اللَّيْل',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Night)"),
    new Surah(
        toPage: 603,
        entitle: "Ad-Duha",
        arbtitle: 'سُوْرَۃُ الضُّحَىٰ',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Early Hours)"),
    new Surah(
        toPage: 603,
        entitle: "Al-Inshirah",
        arbtitle: 'سُوْرَۃُ الشَّرْح',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Opening Up)"),
    new Surah(
        toPage: 604,
        entitle: "At-Tin",
        arbtitle: 'سُوْرَۃُ التِّين',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Fig)"),
    new Surah(
        toPage: 604,
        entitle: "Al-Alaq",
        arbtitle: 'سُوْرَۃُ العَلَق',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Clot)"),
    new Surah(
        toPage: 605,
        entitle: "Al-Qadr",
        arbtitle: 'سُوْرَۃُ القَدْر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Majesty)"),
    new Surah(
        toPage: 605,
        entitle: "Al-Bayyinah",
        arbtitle: 'سُوْرَۃُ البَيِّنَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Clear Evidence)"),
    new Surah(
        toPage: 606,
        entitle: "Al-Zilzal",
        arbtitle: 'سُوْرَۃُ الزَّلْزَلَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Shaking)"),
    new Surah(
        toPage: 606,
        entitle: "Al-Adiyat",
        arbtitle: 'سُوْرَۃُ العَادِيَات',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Assaulters)"),
    new Surah(
        toPage: 607,
        entitle: "Al-Qari'ah",
        arbtitle: 'سُوْرَۃُ القَارِعَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Calamity)"),
    new Surah(
        toPage: 607,
        entitle: "At-Takathur",
        arbtitle: 'سُوْرَۃُ التَّكَاثُر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Rivalry in World Increase)"),
    new Surah(
        toPage: 608,
        entitle: "Al-Asr",
        arbtitle: 'سُوْرَۃُ العَصْر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Time)"),
    new Surah(
        toPage: 608,
        entitle: "Al-Humazah",
        arbtitle: 'سُوْرَۃُ الهُمَزَة',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Slanderer)"),
    new Surah(
        toPage: 608,
        entitle: "Al-Fil",
        arbtitle: 'سُوْرَۃُ الفِيل',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Elephant)"),
    new Surah(
        toPage: 609,
        entitle: "Quraish",
        arbtitle: 'سُوْرَۃ قُرَيْش',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Quraish)"),
    new Surah(
        toPage: 609,
        entitle: "Al-Maun",
        arbtitle: 'سُوْرَۃُ المَاعُون',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(Act of Kindness)"),
    new Surah(
        toPage: 609,
        entitle: "Al-Kauthar",
        arbtitle: 'سُوْرَۃُ الكَوْثَر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Abundance of Good)"),
    new Surah(
        toPage: 609,
        entitle: "Al-Kafirun",
        arbtitle: 'سُوْرَۃُ الكَافِرُون',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Disbelievers)"),
    new Surah(
        toPage: 610,
        entitle: "An-Nasr",
        arbtitle: 'سُوْرَۃُ النَّصْر',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Help)"),
    new Surah(
        toPage: 610,
        entitle: "Al-Lahab",
        arbtitle: 'سُوْرَۃُ المَسَد',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Flame)"),
    new Surah(
        toPage: 610,
        entitle: "Al-Ikhlas",
        arbtitle: 'سُوْرَۃُ الإِخْلَاص',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Unity)"),
    new Surah(
        toPage: 611,
        entitle: "Al-Falaq",
        arbtitle: 'سُوْرَۃُ الفَلَق',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Dawn)"),
    new Surah(
        toPage: 611,
        entitle: "An-Nas",
        arbtitle: 'سُوْرَۃُ النَّاس',
        totalVerses: 0,
        mmTranslation: "",
        enTranslation: "(The Men)"),
  ];
}
